# Generated by Django 5.0.2 on 2024-03-04 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_city_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='dateTempUpdate',
            field=models.DateField(default="2024-02-02", help_text='Enter the date of temp update'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='city',
            name='tempValue',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Enter the temperature', max_digits=3),
            preserve_default=False,
        ),
    ]
