# Generated by Django 5.0.2 on 2024-03-04 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_city_datetempupdate_city_tempvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='dateTempUpdate',
            field=models.DateTimeField(help_text='Enter the date of temp update'),
        ),
    ]
